server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/renga1080/loriini-config-repo
          #username: renga1080@gmail.com
          #password: SriRam@2020
          skipSslValidation:  true
          timeout:  10
